---

- name: Install lvm packages
  ansible.builtin.package:
    package: "{{ lvm_packages }}"
    state: present
  notify:
    - enable lvm2-monitor
  tags: lvm_init

- name: start lvm2-monitor
  service:
    name: lvm2-monitor
    state: restarted
  tags: lvm_init

- name: Create LVG
  lvg:
    pvs: "{{ PV_DEVICES }}"
    vg: "{{ VG_NAME }}"
  tags: lvm_vg

- name: Create thin pools
  lvol:
    vg: "{{ VG_NAME }}"
    thinpool: "{{ item.name }}"
    size: "{{ item.size }}"
    shrink: "{{ item.shrink if item.shrink is defined else 'no' }}"
  loop: "{{ THIN_POOLS }}"
  when: THIN_POOLS is defined
  tags: lvm_thinpool

- name: Create normal LVs
  lvol:
    vg: "{{ VG_NAME }}"
    lv: "{{ item.name }}"
    size: "{{ item.size }}"
  loop: "{{ THICK_LVS }}"
  when: THICK_LVS is defined
  tags: lvm_lv

- name: Create thin LVs
  lvol:
    vg: "{{ VG_NAME }}"
    lv: "{{ item.name }}"
    size: "{{ item.size }}"
    thinpool: "{{ item.thinpool }}"
  loop: "{{ THIN_LVS }}"
  when: THIN_LVS is defined

  tags: lvm_thinlv
