---
# Handlers for lvm role
- name: Enable lvm2-monitor
  ansible.builtin.service:
    name: lvm2-monitor
    enabled: true

- name: Disable lvm2-monitor
  ansible.builtin.service:
    name: lvm2-monitor
    enabled: false

- name: Start lvm2-monitor
  ansible.builtin.service:
    name: lvm2-monitor
    state: started

- name: Stop lvm2-monitor
  ansible.builtin.service:
    name: lvm2-monitor
    state: stopped

- name: Restart lvm2-monitor
  ansible.builtin.service:
    name: lvm2-monitor
    state: restarted

- name: Reload lvm2-monitor
  ansible.builtin.service:
    name: lvm2-monitor
    state: reloaded
